### ISSUE TITLE
Reset the values to null for “Show Total Cash Held” & “Press to collect cash” when the Maintainer successfully pushes “Press Here When Finished.” 

### ISSUE THREAD

**Issue by samratshaw** [footyapps27/nus_vmcs#1]
Reset the values to null for “Show Total Cash Held” & “Press to collect cash” when the Maintainer successfully pushes “Press Here When Finished.” The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held & already collected persists in display. This causes confusion to the Maintainer.

Attached images for the exact change required.

**Current Situation**
![defect_before](https://cloud.githubusercontent.com/assets/6166967/18628935/30b1e5fa-7e95-11e6-9f50-3927be67ff4e.jpeg)

**After fix:**
![defect_after](https://cloud.githubusercontent.com/assets/6166967/18628995/7c8530cc-7e95-11e6-9727-d60fb59b8f53.jpeg)

**Comment by sanjayc87** [comment]
@LinBoYuanGitHub @vdeepakraaj Analyze and create a new Branch Bug_Fix_1.0.8.1. Proceed with Bug Fix Process.

**Comment by vdeepakraaj** [comment]
@sanjayc87 After analyzing, the defect is found in maintenance module and the component affected is MaintenanceConntroller. It seems like a minor fix. 
The Change involves initializing the total cash and collect cash text fields when the maintainer logs out.

**Comment by sanjayc87** [comment]
@vdeepakraaj thank you for the analysis. 
@LinBoYuanGitHub kindly fix the defect as per the analysis.
PS please create the new branch as stated earlier.

**Comment by LinBoYuanGitHub** [comment]
@sanjayc87  Fixed the bugs in MaintenanceConntroller and commit in the Brach Bug_Fix_1.0.8.1.

**Comment by sanjayc87** [comment]
@Premraj-Murugaraj Kindly confirm if the bug has been fixed as expected.

**Comment by Premraj-Murugaraj** [comment]
Test Results:
The defect is retested on following scenario:
1> As a maintainer  On pressing the "Press Here When Finished" the fields are set to null for fields “Show Total Cash Held” & “Press to collect cash”
2>New session is maintained during re-login.

Hence issue is retested and its working as expected.

**Comment by sanjayc87** [comment]
@LinBoYuanGitHub create a Pull Request so that this branch can be merged to the master branch.

**Comment by LinBoYuanGitHub** [comment]
@sanjayc87 Created the pull request & assigned to you. Kindly perform the merge.

**Comment by sanjayc87** [comment]
@Premraj-Murugaraj i have merged the changes to master branch. Kindly test if everything works as expected in master branch.

**Comment by Premraj-Murugaraj** [comment]
Defect is retested and all required regression cases were executed successfully in the current build.
I recommend the build for acceptance testing

**Comment by sanjayc87** [comment]
@footyapps27 This has already been incorporated & is a part of the release with the enhancement.

**Comment by wwb1990** [comment]
Works fine.

**Comment by JoshMarkF** [comment]
Release made. Tag : RC1.0.9

**Comment by samratshaw** [comment]
@JoshMarkF Thank you.
