### ISSUE TITLE
Provide an at a glance display of the cash amount available, by denomination, for collection by the Maintainer.

### ISSUE THREAD

**Issue by samratshaw** [footyapps27/nus_vmcs#2]
The system is required to provide an at a glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” & “Press Collect to Cash” when pressed, thus leaving no room for dispute over system errors.

Attached screen shots.

**Before Fix:**
![before_enahancement](https://cloud.githubusercontent.com/assets/6166967/18629271/1ca54a0a-7e97-11e6-91da-b5ea91297e8d.jpeg)

**After Fix.**
![after_enhancement](https://cloud.githubusercontent.com/assets/6166967/18629285/271864d6-7e97-11e6-8f5d-7046652ceb8f.jpeg)

**Comment by sanjayc87** [comment]
@Zhenchang Kindly proceed with the analysis of the Enhancement.

**Comment by zaocwana** [comment]
@sanjayc87 After analyzing, two modules will be affected by this enhancement. The affected modules are Maintenance & Store.

Kindly let me know which branch to update the design model report in.

**Comment by sanjayc87** [comment]
@Zhenchang Hello Liu, I have created a new branch for the enhancement. Branch name Feature_1.0.9.
Kindly update the design model report with your analysis.

**Comment by zaocwana** [comment]
@sanjayc87 I have updated the DesignModelReport in the feature branch.

**Comment by sanjayc87** [comment]
@Bavithra kindly update the changes as per the updated design model report.

**Comment by Bavithra** [comment]
@sanjayc87 updated the changes and committed the same to the branch Feature_1.0.9 as per design model report. Please verify the same.

**Comment by sanjayc87** [comment]
@Bavithra The changes look good.
@Premraj-Murugaraj kindly verify the implementation.

**Comment by Premraj-Murugaraj** [comment]
Test Result:

> The changes were verified in the documents affected due to this change.
>  Design documents have updated with all changes needed for the enhancement and it have versioning.
> The issue is retested,  The denominations were updated inline to money available in the vending machine.
> Hence issue is retested and its working as expected.

**Comment by sanjayc87** [comment]
@Bavithra kindly create a pull request.

**Comment by Bavithra** [comment]
@sanjayc87 Created the pull request & assigned it to you.

**Comment by sanjayc87** [comment]
@Premraj-Murugaraj i have merged the changes to master. Kindly confirm if nothing is broken. We will go for acceptance testing after your confirmation.

**Comment by Premraj-Murugaraj** [comment]
The released feature is tested and its working a expected.
The regression suite is executed and ensured all existing functionality is not affected.
I recommend the build RC1.0.9 for Acceptance testing

**Comment by sanjayc87** [comment]
@wwb1990 kindly test the master branch. This contains the bug fix(CR01) & enhancement code(CR02). We will release the code to RM after your confirmation.

**Comment by wwb1990** [comment]
Works fine and can proceed for production.
Take this my sign-off.

**Comment by sanjayc87** [comment]
@footyapps27 kindly assign the code for release.

**Comment by samratshaw** [comment]
@JoshMarkF Kindly package a new release. Release ID-RC1.0.9

**Comment by JoshMarkF** [comment]
Release made. Tag : RC1.0.9

**Comment by samratshaw** [comment]
@JoshMarkF Thank you.
